### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by gaoyuanzong** [XunMengWinter/PetNote-oss#3]
Build input file cannot be found: '/Users/ice/Documents/work/wefor/ios/MYMX/Bridging-Header.h'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

**Comment by peteisacat** [comment]
把文件Bridging-Header.h从Build Settings里面删除就好了

**Comment by peteisacat** [comment]
> Build input file cannot be found: '/Users/ice/Documents/work/wefor/ios/MYMX/Bridging-Header.h'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?


**把文件Bridging-Header.h从Build Settings里面删除就好了**

**Comment by XunMengWinter** [comment]
> > Build input file cannot be found: '/Users/ice/Documents/work/wefor/ios/MYMX/Bridging-Header.h'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?
> 
> **把文件Bridging-Header.h从Build Settings里面删除就好了**

是的，以及修复提交新的代码了
